# 服务端口
server:
  port: 8078

# datax路径
#datax:
#  binpath: D:\\datax\\bin\\datax.py
#  jsonpath: D:\\datax\\job\\

# dubbo配置
dubbo:
  registry:
    address: zookeeper://192.168.30.18:2181?backup=192.168.30.16:2181,192.168.30.17:2181 # zookeeper 地址
  port: 30001 # 注册dubbo端口

# 应用名称
spring:
  application:
    name: datax-manager
