server:
  port: 8078

datax:
  binpath: D:\\datax\\bin\\datax.py
  jsonpath: D:\\datax\\job\\

dubbo:
  registry:
    address: 192.168.30.18:2181
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/summer?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#

spring:
  application:
    name: datax-manager
